@startuml ER
entity "users" {
  id [PK]
  --
  email [メールアドレス（未設定）]
  password [パスワード（未設定）]
  name [名前]
  coin [手持ちコイン]
  picture [プロフィール写真]
  life_flag [アカウントが有効かどうかのフラグ]
}
entity "board" {
  id [PK]
  --
  user_id [投稿者のid]
  board_content [投稿の中身]
  created_at [作成時間]
}
entity "bet_contents" {
  id [PK]
  --
  title [賭けのタイトル]
  text [賭けの内容]
  picture_name [写真の名前]
  bet_genre [賭けのジャンル]
  bet_content_name_A [賭ける物の名前A]
  bet_content_name_B [賭ける物の名前B]
  total_bet_coin_A [Aに賭けられたコインの総額]
  total_bet_coin_B [Bに賭けられたコインの総額]
  expiration [賭けの期限]
  status [賭けの状況]
}
entity "bet_coin" {
  id [PK]
  --
  user_id [賭けをしたユーザーのID]
  bet_contents_id [賭けたコンテンツのID]
  which [賭けた方]
  bet_coin_amount [賭けたコインの額]
}
users ||--o{ board
users ||--{ bet_coin
bet_coin ||--|| bet_contents
@enduml