name: test in client

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use node 14
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: npm install
        working-directory: ./client
        run: npm install
      - name: npm run test
        working-directory: ./client
        run: npm run test
