name: test in server

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: npm install
        working-directory: ./server
        run: npm install
      - name: npm run test
        working-directory: ./server
        run: npm run test